/*
 * File: TMS320F28335.c
 *
 *
 *   --- THIS FILE GENERATED BY S-FUNCTION BUILDER: 3.0 ---
 *
 *   This file is an S-function produced by the S-Function
 *   Builder which only recognizes certain fields.  Changes made
 *   outside these fields will be lost the next time the block is
 *   used to load, edit, and resave this file. This file will be overwritten
 *   by the S-function Builder block. If you want to edit this file by hand, 
 *   you must change it only in the area defined as:  
 *
 *        %%%-SFUNWIZ_defines_Changes_BEGIN
 *        #define NAME 'replacement text' 
 *        %%% SFUNWIZ_defines_Changes_END
 *
 *   DO NOT change NAME--Change the 'replacement text' only.
 *
 *   For better compatibility with the Simulink Coder, the
 *   "wrapper" S-function technique is used.  This is discussed
 *   in the Simulink Coder's Manual in the Chapter titled,
 *   "Wrapper S-functions".
 *
 *  -------------------------------------------------------------------------
 * | See matlabroot/simulink/src/sfuntmpl_doc.c for a more detailed template |
 *  ------------------------------------------------------------------------- 
 *
 * Created: Mon Mar 08 18:51:02 2021
 */

#define S_FUNCTION_LEVEL 2
#define S_FUNCTION_NAME TMS320F28335
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
/* %%%-SFUNWIZ_defines_Changes_BEGIN --- EDIT HERE TO _END */
#define NUM_INPUTS            3
/* Input Port  0 */
#define IN_PORT_0_NAME        Lpars
#define INPUT_0_WIDTH         7
#define INPUT_DIMS_0_COL      1
#define INPUT_0_DTYPE         real_T
#define INPUT_0_COMPLEX       COMPLEX_NO
#define IN_0_FRAME_BASED      FRAME_NO
#define IN_0_BUS_BASED        0
#define IN_0_BUS_NAME         
#define IN_0_DIMS             1-D
#define INPUT_0_FEEDTHROUGH   1
#define IN_0_ISSIGNED         0
#define IN_0_WORDLENGTH       8
#define IN_0_FIXPOINTSCALING  1
#define IN_0_FRACTIONLENGTH   9
#define IN_0_BIAS             0
#define IN_0_SLOPE            0.125
/* Input Port  1 */
#define IN_PORT_1_NAME        Rpars
#define INPUT_1_WIDTH         7
#define INPUT_DIMS_1_COL      1
#define INPUT_1_DTYPE         real_T
#define INPUT_1_COMPLEX       COMPLEX_NO
#define IN_1_FRAME_BASED      FRAME_NO
#define IN_1_BUS_BASED        0
#define IN_1_BUS_NAME         
#define IN_1_DIMS             1-D
#define INPUT_1_FEEDTHROUGH   1
#define IN_1_ISSIGNED         0
#define IN_1_WORDLENGTH       8
#define IN_1_FIXPOINTSCALING  1
#define IN_1_FRACTIONLENGTH   9
#define IN_1_BIAS             0
#define IN_1_SLOPE            0.125
/* Input Port  2 */
#define IN_PORT_2_NAME        FromKabine
#define INPUT_2_WIDTH         3
#define INPUT_DIMS_2_COL      1
#define INPUT_2_DTYPE         real_T
#define INPUT_2_COMPLEX       COMPLEX_NO
#define IN_2_FRAME_BASED      FRAME_NO
#define IN_2_BUS_BASED        0
#define IN_2_BUS_NAME         
#define IN_2_DIMS             1-D
#define INPUT_2_FEEDTHROUGH   1
#define IN_2_ISSIGNED         0
#define IN_2_WORDLENGTH       8
#define IN_2_FIXPOINTSCALING  1
#define IN_2_FRACTIONLENGTH   9
#define IN_2_BIAS             0
#define IN_2_SLOPE            0.125

#define NUM_OUTPUTS           3
/* Output Port  0 */
#define OUT_PORT_0_NAME       PWM
#define OUTPUT_0_WIDTH        7
#define OUTPUT_DIMS_0_COL     1
#define OUTPUT_0_DTYPE        real_T
#define OUTPUT_0_COMPLEX      COMPLEX_NO
#define OUT_0_FRAME_BASED     FRAME_NO
#define OUT_0_BUS_BASED       0
#define OUT_0_BUS_NAME        
#define OUT_0_DIMS            1-D
#define OUT_0_ISSIGNED        1
#define OUT_0_WORDLENGTH      8
#define OUT_0_FIXPOINTSCALING 1
#define OUT_0_FRACTIONLENGTH  3
#define OUT_0_BIAS            0
#define OUT_0_SLOPE           0.125
/* Output Port  1 */
#define OUT_PORT_1_NAME       Out_L
#define OUTPUT_1_WIDTH        1
#define OUTPUT_DIMS_1_COL     1
#define OUTPUT_1_DTYPE        real_T
#define OUTPUT_1_COMPLEX      COMPLEX_NO
#define OUT_1_FRAME_BASED     FRAME_NO
#define OUT_1_BUS_BASED       1
#define OUT_1_BUS_NAME        DebugInfL
#define OUT_1_DIMS            1-D
#define OUT_1_ISSIGNED        1
#define OUT_1_WORDLENGTH      8
#define OUT_1_FIXPOINTSCALING 1
#define OUT_1_FRACTIONLENGTH  3
#define OUT_1_BIAS            0
#define OUT_1_SLOPE           0.125
/* Output Port  2 */
#define OUT_PORT_2_NAME       Out_R
#define OUTPUT_2_WIDTH        1
#define OUTPUT_DIMS_2_COL     1
#define OUTPUT_2_DTYPE        real_T
#define OUTPUT_2_COMPLEX      COMPLEX_NO
#define OUT_2_FRAME_BASED     FRAME_NO
#define OUT_2_BUS_BASED       1
#define OUT_2_BUS_NAME        DebugInfR
#define OUT_2_DIMS            1-D
#define OUT_2_ISSIGNED        1
#define OUT_2_WORDLENGTH      8
#define OUT_2_FIXPOINTSCALING 1
#define OUT_2_FRACTIONLENGTH  3
#define OUT_2_BIAS            0
#define OUT_2_SLOPE           0.125

#define NPARAMS               0

#define SAMPLE_TIME_0         0.000666
#define NUM_DISC_STATES       0
#define DISC_STATES_IC        [0]
#define NUM_CONT_STATES       0
#define CONT_STATES_IC        [0]

#define SFUNWIZ_GENERATE_TLC  1
#define SOURCEFILES           "__SFB__BELAZ_450_DRIVE\source\RegL.c__SFB__BELAZ_450_DRIVE\source\RegR.c__SFB__BELAZ_450_DRIVE\source\func.c"
#define PANELINDEX            8
#define USE_SIMSTRUCT         0
#define SHOW_COMPILE_STEPS    0
#define CREATE_DEBUG_MEXFILE  0
#define SAVE_CODE_ONLY        0
#define SFUNWIZ_REVISION      3.0
/* %%%-SFUNWIZ_defines_Changes_END --- EDIT HERE TO _BEGIN */
/*<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<*/
#include "simstruc.h"
#include "TMS320F28335_bus.h"
/*
 * Code Generation Environment flag (simulation or standalone target).
 */
 static int_T isSimulationTarget;
/* Utility function prototypes. */
static int_T GetRTWEnvironmentMode(SimStruct *S);
/* Macro used to check if Simulation mode is set to accelerator */
#define isBusDWorkPresent  ( ( ( !ssRTWGenIsCodeGen(S) || isSimulationTarget ) && !ssIsExternalSim(S) ) || ssIsRapidAcceleratorActive(S) )

typedef struct {
    int_T offset;
    int_T elemSize;
    int_T numElems;
} busInfoStruct;

extern void TMS320F28335_Outputs_wrapper(const real_T *Lpars,
			const real_T *Rpars,
			const real_T *FromKabine,
			real_T *PWM,
			DebugInfL *Out_L,
			DebugInfR *Out_R);
/*====================*
 * S-function methods *
 *====================*/
/* Function: mdlInitializeSizes ===============================================
 * Abstract:
 *   Setup sizes of the various vectors.
 */
static void mdlInitializeSizes(SimStruct *S)
{

    DECL_AND_INIT_DIMSINFO(inputDimsInfo);
    DECL_AND_INIT_DIMSINFO(outputDimsInfo);
    ssSetNumSFcnParams(S, NPARAMS);
    if (ssGetNumSFcnParams(S) != ssGetSFcnParamsCount(S)) {
        return; /* Parameter mismatch will be reported by Simulink */
    }

    ssSetArrayLayoutForCodeGen(S, SS_COLUMN_MAJOR);

    ssSetOperatingPointCompliance(S, USE_DEFAULT_OPERATING_POINT);

    ssSetNumContStates(S, NUM_CONT_STATES);
    ssSetNumDiscStates(S, NUM_DISC_STATES);


    if (!ssSetNumInputPorts(S, NUM_INPUTS)) return;
    /* Input Port 0 */
    ssSetInputPortWidth(S, 0, INPUT_0_WIDTH);
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 0, INPUT_0_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 0, INPUT_0_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 0, 1); /*direct input signal access*/

    /* Input Port 1 */
    ssSetInputPortWidth(S, 1, INPUT_1_WIDTH);
    ssSetInputPortDataType(S, 1, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 1, INPUT_1_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 1, INPUT_1_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 1, 1); /*direct input signal access*/

    /* Input Port 2 */
    ssSetInputPortWidth(S, 2, INPUT_2_WIDTH);
    ssSetInputPortDataType(S, 2, SS_DOUBLE);
    ssSetInputPortComplexSignal(S, 2, INPUT_2_COMPLEX);
    ssSetInputPortDirectFeedThrough(S, 2, INPUT_2_FEEDTHROUGH);
    ssSetInputPortRequiredContiguous(S, 2, 1); /*direct input signal access*/


    if (!ssSetNumOutputPorts(S, NUM_OUTPUTS)) return;
    /* Output Port 0 */
    ssSetOutputPortWidth(S, 0, OUTPUT_0_WIDTH);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortComplexSignal(S, 0, OUTPUT_0_COMPLEX);
    /* Output Port 1 */

  /* Register DebugInfL datatype for Output port 1 */

    #if defined(MATLAB_MEX_FILE)
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY)
    {
      DTypeId dataTypeIdReg;
      ssRegisterTypeFromNamedObject(S, "DebugInfL", &dataTypeIdReg);
      if(dataTypeIdReg == INVALID_DTYPE_ID) return;
        ssSetOutputPortDataType(S, 1, dataTypeIdReg);
    }
    #endif

    ssSetBusOutputObjectName(S, 1, (void *) "DebugInfL");
    ssSetOutputPortWidth(S, 1, OUTPUT_1_WIDTH);
    ssSetOutputPortComplexSignal(S, 1, OUTPUT_1_COMPLEX);
    ssSetBusOutputAsStruct(S, 1,OUT_1_BUS_BASED);
    ssSetOutputPortBusMode(S, 1, SL_BUS_MODE);
    /* Output Port 2 */

  /* Register DebugInfR datatype for Output port 2 */

    #if defined(MATLAB_MEX_FILE)
    if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY)
    {
      DTypeId dataTypeIdReg;
      ssRegisterTypeFromNamedObject(S, "DebugInfR", &dataTypeIdReg);
      if(dataTypeIdReg == INVALID_DTYPE_ID) return;
        ssSetOutputPortDataType(S, 2, dataTypeIdReg);
    }
    #endif

    ssSetBusOutputObjectName(S, 2, (void *) "DebugInfR");
    ssSetOutputPortWidth(S, 2, OUTPUT_2_WIDTH);
    ssSetOutputPortComplexSignal(S, 2, OUTPUT_2_COMPLEX);
    ssSetBusOutputAsStruct(S, 2,OUT_2_BUS_BASED);
    ssSetOutputPortBusMode(S, 2, SL_BUS_MODE);

    if (ssRTWGenIsCodeGen(S)) {
        isSimulationTarget = GetRTWEnvironmentMode(S);
        if (isSimulationTarget == -1) {
            ssSetErrorStatus(S, " Unable to determine a valid code generation environment mode");
            return;
        }
        isSimulationTarget |= ssRTWGenIsModelReferenceSimTarget(S);
    }
    
    /* Set the number of dworks */
    if (!isBusDWorkPresent) {
        if (!ssSetNumDWork(S, 0)) return;
    } else {
        if (!ssSetNumDWork(S, 2)) return;
    }

    if (isBusDWorkPresent) {

      /*
       * Configure the dwork 0 (Out_LBUS)
       */
#if defined(MATLAB_MEX_FILE)
      if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;
        ssRegisterTypeFromNamedObject(S, "DebugInfL", &dataTypeIdReg);
        if (dataTypeIdReg == INVALID_DTYPE_ID) return;
        ssSetDWorkDataType(S, 0, dataTypeIdReg);
      }
#endif
      
      ssSetDWorkUsageType(S, 0, SS_DWORK_USED_AS_DWORK);
      ssSetDWorkName(S, 0, "Out_LBUS");
      ssSetDWorkWidth(S, 0, DYNAMICALLY_SIZED);
      ssSetDWorkComplexSignal(S, 0, COMPLEX_NO);

      /*
       * Configure the dwork 1 (Out_RBUS)
       */
#if defined(MATLAB_MEX_FILE)
      if (ssGetSimMode(S) != SS_SIMMODE_SIZES_CALL_ONLY) {
        DTypeId dataTypeIdReg;
        ssRegisterTypeFromNamedObject(S, "DebugInfR", &dataTypeIdReg);
        if (dataTypeIdReg == INVALID_DTYPE_ID) return;
        ssSetDWorkDataType(S, 1, dataTypeIdReg);
      }
#endif
      
      ssSetDWorkUsageType(S, 1, SS_DWORK_USED_AS_DWORK);
      ssSetDWorkName(S, 1, "Out_RBUS");
      ssSetDWorkWidth(S, 1, DYNAMICALLY_SIZED);
      ssSetDWorkComplexSignal(S, 1, COMPLEX_NO);
    }
    ssSetNumPWork(S, 0);

    ssSetNumSampleTimes(S, 1);
    ssSetNumRWork(S, 0);
    ssSetNumIWork(S, 0);
    ssSetNumModes(S, 0);
    ssSetNumNonsampledZCs(S, 0);

    ssSetSimulinkVersionGeneratedIn(S, "9.3");

    /* Take care when specifying exception free code - see sfuntmpl_doc.c */
    ssSetOptions(S, (SS_OPTION_EXCEPTION_FREE_CODE |
                     SS_OPTION_USE_TLC_WITH_ACCELERATOR |
                     SS_OPTION_WORKS_WITH_CODE_REUSE));
}

#if defined(MATLAB_MEX_FILE)
#define MDL_SET_INPUT_PORT_DIMENSION_INFO
static void mdlSetInputPortDimensionInfo(SimStruct        *S, 
                                         int_T            port,
                                         const DimsInfo_T *dimsInfo)
{
    if(!ssSetInputPortDimensionInfo(S, port, dimsInfo)) return;
}
#endif

#define MDL_SET_OUTPUT_PORT_DIMENSION_INFO
#if defined(MDL_SET_OUTPUT_PORT_DIMENSION_INFO)
static void mdlSetOutputPortDimensionInfo(SimStruct        *S, 
                                          int_T            port, 
                                          const DimsInfo_T *dimsInfo)
{
    if (!ssSetOutputPortDimensionInfo(S, port, dimsInfo)) return;
}
#endif

/* Function: mdlInitializeSampleTimes =========================================
 * Abstract:
 *    Specifiy  the sample time.
 */
static void mdlInitializeSampleTimes(SimStruct *S)
{
    ssSetSampleTime(S, 0, SAMPLE_TIME_0);
    ssSetModelReferenceSampleTimeDefaultInheritance(S);
    ssSetOffsetTime(S, 0, 0.0);
}

#define MDL_SET_INPUT_PORT_DATA_TYPE
static void mdlSetInputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetInputPortDataType(S, 0, dType);
}

#define MDL_SET_OUTPUT_PORT_DATA_TYPE
static void mdlSetOutputPortDataType(SimStruct *S, int port, DTypeId dType)
{
    ssSetOutputPortDataType(S, 0, dType);
}

#define MDL_SET_DEFAULT_PORT_DATA_TYPES
static void mdlSetDefaultPortDataTypes(SimStruct *S)
{
    ssSetInputPortDataType(S, 0, SS_DOUBLE);
    ssSetOutputPortDataType(S, 0, SS_DOUBLE);
}

#define MDL_SET_WORK_WIDTHS
#if defined(MDL_SET_WORK_WIDTHS) && defined(MATLAB_MEX_FILE)

static void mdlSetWorkWidths(SimStruct *S)
{
/* Set the width of DWork(s) used for marshalling the IOs */
    if (isBusDWorkPresent) {

        /* Update dwork 0 */
        ssSetDWorkWidth(S, 0, ssGetOutputPortWidth(S, 1));

        /* Update dwork 1 */
        ssSetDWorkWidth(S, 1, ssGetOutputPortWidth(S, 2));

    }

}

#endif

#define MDL_START  /* Change to #undef to remove function */
#if defined(MDL_START)
/* Function: mdlStart =======================================================
 * Abstract:
 *    This function is called once at start of model execution. If you
 *    have states that should be initialized once, this is the place
 *    to do it.
 */
static void mdlStart(SimStruct *S)
{
    /* Bus Information */
    slDataTypeAccess *dta = ssGetDataTypeAccess(S);
    const char *bpath = ssGetPath(S);
	DTypeId DebugInfLId = ssGetDataTypeId(S, "DebugInfL");
	DTypeId DebugInfRId = ssGetDataTypeId(S, "DebugInfR");

	busInfoStruct *busInfo = (busInfoStruct *)malloc(346*sizeof(busInfoStruct));
	if(busInfo==NULL) {
        ssSetErrorStatus(S, "Memory allocation failure");
        return;
    }

      /* Calculate offsets of all primitive elements of the bus */

	busInfo[0].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 0);
	busInfo[0].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[0].numElems = 1;
	busInfo[1].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 1);
	busInfo[1].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[1].numElems = 1;
	busInfo[2].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 2);
	busInfo[2].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[2].numElems = 1;
	busInfo[3].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 3);
	busInfo[3].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[3].numElems = 1;
	busInfo[4].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 4);
	busInfo[4].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[4].numElems = 1;
	busInfo[5].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 5);
	busInfo[5].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[5].numElems = 1;
	busInfo[6].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 6);
	busInfo[6].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[6].numElems = 1;
	busInfo[7].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 7);
	busInfo[7].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[7].numElems = 1;
	busInfo[8].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 8);
	busInfo[8].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[8].numElems = 1;
	busInfo[9].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 9);
	busInfo[9].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[9].numElems = 1;
	busInfo[10].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 10);
	busInfo[10].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[10].numElems = 1;
	busInfo[11].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 11);
	busInfo[11].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[11].numElems = 1;
	busInfo[12].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 12);
	busInfo[12].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[12].numElems = 1;
	busInfo[13].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 13);
	busInfo[13].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[13].numElems = 1;
	busInfo[14].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 14);
	busInfo[14].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[14].numElems = 1;
	busInfo[15].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 15);
	busInfo[15].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[15].numElems = 1;
	busInfo[16].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 16);
	busInfo[16].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[16].numElems = 1;
	busInfo[17].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 17);
	busInfo[17].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[17].numElems = 1;
	busInfo[18].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 18);
	busInfo[18].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[18].numElems = 1;
	busInfo[19].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 19);
	busInfo[19].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[19].numElems = 1;
	busInfo[20].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 20);
	busInfo[20].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[20].numElems = 1;
	busInfo[21].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 21);
	busInfo[21].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[21].numElems = 1;
	busInfo[22].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 22);
	busInfo[22].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[22].numElems = 1;
	busInfo[23].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 23);
	busInfo[23].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[23].numElems = 1;
	busInfo[24].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 24);
	busInfo[24].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[24].numElems = 1;
	busInfo[25].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 25);
	busInfo[25].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[25].numElems = 1;
	busInfo[26].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 26);
	busInfo[26].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[26].numElems = 1;
	busInfo[27].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 27);
	busInfo[27].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[27].numElems = 1;
	busInfo[28].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 28);
	busInfo[28].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[28].numElems = 1;
	busInfo[29].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 29);
	busInfo[29].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[29].numElems = 1;
	busInfo[30].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 30);
	busInfo[30].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[30].numElems = 1;
	busInfo[31].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 31);
	busInfo[31].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[31].numElems = 1;
	busInfo[32].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 32);
	busInfo[32].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[32].numElems = 1;
	busInfo[33].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 33);
	busInfo[33].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[33].numElems = 1;
	busInfo[34].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 34);
	busInfo[34].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[34].numElems = 1;
	busInfo[35].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 35);
	busInfo[35].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[35].numElems = 1;
	busInfo[36].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 36);
	busInfo[36].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[36].numElems = 1;
	busInfo[37].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 37);
	busInfo[37].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[37].numElems = 1;
	busInfo[38].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 38);
	busInfo[38].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[38].numElems = 1;
	busInfo[39].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 39);
	busInfo[39].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[39].numElems = 1;
	busInfo[40].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 40);
	busInfo[40].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[40].numElems = 1;
	busInfo[41].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 41);
	busInfo[41].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[41].numElems = 1;
	busInfo[42].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 42);
	busInfo[42].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[42].numElems = 1;
	busInfo[43].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 43);
	busInfo[43].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[43].numElems = 1;
	busInfo[44].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 44);
	busInfo[44].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[44].numElems = 1;
	busInfo[45].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 45);
	busInfo[45].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[45].numElems = 1;
	busInfo[46].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 46);
	busInfo[46].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[46].numElems = 1;
	busInfo[47].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 47);
	busInfo[47].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[47].numElems = 1;
	busInfo[48].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 48);
	busInfo[48].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[48].numElems = 1;
	busInfo[49].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 49);
	busInfo[49].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[49].numElems = 1;
	busInfo[50].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 50);
	busInfo[50].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[50].numElems = 1;
	busInfo[51].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 51);
	busInfo[51].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[51].numElems = 1;
	busInfo[52].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 52);
	busInfo[52].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[52].numElems = 1;
	busInfo[53].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 53);
	busInfo[53].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[53].numElems = 1;
	busInfo[54].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 54);
	busInfo[54].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[54].numElems = 1;
	busInfo[55].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 55);
	busInfo[55].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[55].numElems = 1;
	busInfo[56].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 56);
	busInfo[56].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[56].numElems = 1;
	busInfo[57].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 57);
	busInfo[57].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[57].numElems = 1;
	busInfo[58].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 58);
	busInfo[58].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[58].numElems = 1;
	busInfo[59].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 59);
	busInfo[59].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[59].numElems = 1;
	busInfo[60].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 60);
	busInfo[60].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[60].numElems = 1;
	busInfo[61].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 61);
	busInfo[61].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[61].numElems = 1;
	busInfo[62].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 62);
	busInfo[62].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[62].numElems = 1;
	busInfo[63].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 63);
	busInfo[63].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[63].numElems = 1;
	busInfo[64].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 64);
	busInfo[64].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[64].numElems = 1;
	busInfo[65].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 65);
	busInfo[65].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[65].numElems = 1;
	busInfo[66].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 66);
	busInfo[66].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[66].numElems = 1;
	busInfo[67].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 67);
	busInfo[67].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[67].numElems = 1;
	busInfo[68].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 68);
	busInfo[68].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[68].numElems = 1;
	busInfo[69].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 69);
	busInfo[69].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[69].numElems = 1;
	busInfo[70].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 70);
	busInfo[70].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[70].numElems = 1;
	busInfo[71].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 71);
	busInfo[71].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[71].numElems = 1;
	busInfo[72].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 72);
	busInfo[72].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[72].numElems = 1;
	busInfo[73].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 73);
	busInfo[73].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[73].numElems = 1;
	busInfo[74].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 74);
	busInfo[74].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[74].numElems = 1;
	busInfo[75].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 75);
	busInfo[75].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[75].numElems = 1;
	busInfo[76].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 76);
	busInfo[76].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[76].numElems = 1;
	busInfo[77].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 77);
	busInfo[77].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[77].numElems = 1;
	busInfo[78].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 78);
	busInfo[78].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[78].numElems = 1;
	busInfo[79].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 79);
	busInfo[79].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[79].numElems = 1;
	busInfo[80].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 80);
	busInfo[80].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[80].numElems = 1;
	busInfo[81].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 81);
	busInfo[81].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[81].numElems = 1;
	busInfo[82].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 82);
	busInfo[82].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[82].numElems = 1;
	busInfo[83].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 83);
	busInfo[83].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[83].numElems = 1;
	busInfo[84].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 84);
	busInfo[84].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[84].numElems = 1;
	busInfo[85].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 85);
	busInfo[85].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[85].numElems = 1;
	busInfo[86].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 86);
	busInfo[86].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[86].numElems = 1;
	busInfo[87].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 87);
	busInfo[87].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[87].numElems = 1;
	busInfo[88].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 88);
	busInfo[88].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[88].numElems = 1;
	busInfo[89].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 89);
	busInfo[89].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[89].numElems = 1;
	busInfo[90].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 90);
	busInfo[90].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[90].numElems = 1;
	busInfo[91].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 91);
	busInfo[91].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[91].numElems = 1;
	busInfo[92].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 92);
	busInfo[92].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[92].numElems = 1;
	busInfo[93].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 93);
	busInfo[93].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[93].numElems = 1;
	busInfo[94].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 94);
	busInfo[94].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[94].numElems = 1;
	busInfo[95].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 95);
	busInfo[95].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[95].numElems = 1;
	busInfo[96].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 96);
	busInfo[96].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[96].numElems = 1;
	busInfo[97].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfLId, 97);
	busInfo[97].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[97].numElems = 1;
	busInfo[98].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 0);
	busInfo[98].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[98].numElems = 1;
	busInfo[99].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 1);
	busInfo[99].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[99].numElems = 1;
	busInfo[100].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 2);
	busInfo[100].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[100].numElems = 1;
	busInfo[101].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 3);
	busInfo[101].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[101].numElems = 1;
	busInfo[102].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 4);
	busInfo[102].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[102].numElems = 1;
	busInfo[103].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 5);
	busInfo[103].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[103].numElems = 1;
	busInfo[104].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 6);
	busInfo[104].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[104].numElems = 1;
	busInfo[105].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 7);
	busInfo[105].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[105].numElems = 1;
	busInfo[106].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 8);
	busInfo[106].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[106].numElems = 1;
	busInfo[107].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 9);
	busInfo[107].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[107].numElems = 1;
	busInfo[108].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 10);
	busInfo[108].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[108].numElems = 1;
	busInfo[109].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 11);
	busInfo[109].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[109].numElems = 1;
	busInfo[110].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 12);
	busInfo[110].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[110].numElems = 1;
	busInfo[111].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 13);
	busInfo[111].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[111].numElems = 1;
	busInfo[112].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 14);
	busInfo[112].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[112].numElems = 1;
	busInfo[113].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 15);
	busInfo[113].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[113].numElems = 1;
	busInfo[114].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 16);
	busInfo[114].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[114].numElems = 1;
	busInfo[115].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 17);
	busInfo[115].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[115].numElems = 1;
	busInfo[116].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 18);
	busInfo[116].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[116].numElems = 1;
	busInfo[117].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 19);
	busInfo[117].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[117].numElems = 1;
	busInfo[118].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 20);
	busInfo[118].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[118].numElems = 1;
	busInfo[119].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 21);
	busInfo[119].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[119].numElems = 1;
	busInfo[120].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 22);
	busInfo[120].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[120].numElems = 1;
	busInfo[121].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 23);
	busInfo[121].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[121].numElems = 1;
	busInfo[122].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 24);
	busInfo[122].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[122].numElems = 1;
	busInfo[123].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 25);
	busInfo[123].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[123].numElems = 1;
	busInfo[124].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 26);
	busInfo[124].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[124].numElems = 1;
	busInfo[125].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 27);
	busInfo[125].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[125].numElems = 1;
	busInfo[126].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 28);
	busInfo[126].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[126].numElems = 1;
	busInfo[127].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 29);
	busInfo[127].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[127].numElems = 1;
	busInfo[128].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 30);
	busInfo[128].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[128].numElems = 1;
	busInfo[129].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 31);
	busInfo[129].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[129].numElems = 1;
	busInfo[130].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 32);
	busInfo[130].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[130].numElems = 1;
	busInfo[131].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 33);
	busInfo[131].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[131].numElems = 1;
	busInfo[132].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 34);
	busInfo[132].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[132].numElems = 1;
	busInfo[133].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 35);
	busInfo[133].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[133].numElems = 1;
	busInfo[134].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 36);
	busInfo[134].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[134].numElems = 1;
	busInfo[135].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 37);
	busInfo[135].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[135].numElems = 1;
	busInfo[136].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 38);
	busInfo[136].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[136].numElems = 1;
	busInfo[137].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 39);
	busInfo[137].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[137].numElems = 1;
	busInfo[138].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 40);
	busInfo[138].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[138].numElems = 1;
	busInfo[139].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 41);
	busInfo[139].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[139].numElems = 1;
	busInfo[140].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 42);
	busInfo[140].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[140].numElems = 1;
	busInfo[141].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 43);
	busInfo[141].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[141].numElems = 1;
	busInfo[142].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 44);
	busInfo[142].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[142].numElems = 1;
	busInfo[143].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 45);
	busInfo[143].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[143].numElems = 1;
	busInfo[144].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 46);
	busInfo[144].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[144].numElems = 1;
	busInfo[145].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 47);
	busInfo[145].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[145].numElems = 1;
	busInfo[146].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 48);
	busInfo[146].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[146].numElems = 1;
	busInfo[147].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 49);
	busInfo[147].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[147].numElems = 1;
	busInfo[148].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 50);
	busInfo[148].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[148].numElems = 1;
	busInfo[149].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 51);
	busInfo[149].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[149].numElems = 1;
	busInfo[150].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 52);
	busInfo[150].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[150].numElems = 1;
	busInfo[151].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 53);
	busInfo[151].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[151].numElems = 1;
	busInfo[152].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 54);
	busInfo[152].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[152].numElems = 1;
	busInfo[153].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 55);
	busInfo[153].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[153].numElems = 1;
	busInfo[154].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 56);
	busInfo[154].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[154].numElems = 1;
	busInfo[155].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 57);
	busInfo[155].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[155].numElems = 1;
	busInfo[156].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 58);
	busInfo[156].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[156].numElems = 1;
	busInfo[157].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 59);
	busInfo[157].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[157].numElems = 1;
	busInfo[158].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 60);
	busInfo[158].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[158].numElems = 1;
	busInfo[159].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 61);
	busInfo[159].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[159].numElems = 1;
	busInfo[160].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 62);
	busInfo[160].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[160].numElems = 1;
	busInfo[161].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 63);
	busInfo[161].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[161].numElems = 1;
	busInfo[162].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 64);
	busInfo[162].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[162].numElems = 1;
	busInfo[163].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 65);
	busInfo[163].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[163].numElems = 1;
	busInfo[164].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 66);
	busInfo[164].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[164].numElems = 1;
	busInfo[165].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 67);
	busInfo[165].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[165].numElems = 1;
	busInfo[166].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 68);
	busInfo[166].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[166].numElems = 1;
	busInfo[167].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 69);
	busInfo[167].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[167].numElems = 1;
	busInfo[168].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 70);
	busInfo[168].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[168].numElems = 1;
	busInfo[169].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 71);
	busInfo[169].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[169].numElems = 1;
	busInfo[170].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 72);
	busInfo[170].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[170].numElems = 1;
	busInfo[171].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 73);
	busInfo[171].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[171].numElems = 1;
	busInfo[172].offset   = dtaGetDataTypeElementOffset(dta, bpath, DebugInfRId, 74);
	busInfo[172].elemSize = dtaGetDataTypeSize(dta, bpath, ssGetDataTypeId(S, "double"));
	busInfo[172].numElems = 1;
	ssSetUserData(S, busInfo);
}
#endif /*  MDL_START */

/* Function: mdlOutputs =======================================================
 *
 */
static void mdlOutputs(SimStruct *S, int_T tid)
{
    const real_T *Lpars = (real_T *) ssGetInputPortRealSignal(S, 0);
    const real_T *Rpars = (real_T *) ssGetInputPortRealSignal(S, 1);
    const real_T *FromKabine = (real_T *) ssGetInputPortRealSignal(S, 2);
    real_T *PWM = (real_T *) ssGetOutputPortRealSignal(S, 0);
    char *Out_L = (char *) ssGetOutputPortSignal(S, 1);
    char *Out_R = (char *) ssGetOutputPortSignal(S, 2);

	busInfoStruct* busInfo = (busInfoStruct *) ssGetUserData(S);

	/* Temporary bus copy declarations */
	DebugInfL _Out_LBUS;
	DebugInfR _Out_RBUS;

	/* Copy input bus into temporary structure */

    TMS320F28335_Outputs_wrapper(Lpars, Rpars, FromKabine, PWM, &_Out_LBUS, &_Out_RBUS);

	/* Copy temporary structure into output bus */
	(void) memcpy(Out_L + busInfo[0].offset, &_Out_LBUS.DeltaSpeedLCruize, busInfo[0].elemSize * busInfo[0].numElems);
	(void) memcpy(Out_L + busInfo[1].offset, &_Out_LBUS.SpeedLzCruize, busInfo[1].elemSize * busInfo[1].numElems);
	(void) memcpy(Out_L + busInfo[2].offset, &_Out_LBUS.AverageCarSpeed, busInfo[2].elemSize * busInfo[2].numElems);
	(void) memcpy(Out_L + busInfo[3].offset, &_Out_LBUS.CruizeDriveL, busInfo[3].elemSize * busInfo[3].numElems);
	(void) memcpy(Out_L + busInfo[4].offset, &_Out_LBUS.DeltaSpeedLABS, busInfo[4].elemSize * busInfo[4].numElems);
	(void) memcpy(Out_L + busInfo[5].offset, &_Out_LBUS.DeltaAxleSpeedL, busInfo[5].elemSize * busInfo[5].numElems);
	(void) memcpy(Out_L + busInfo[6].offset, &_Out_LBUS.DeltaAxleSpeedR, busInfo[6].elemSize * busInfo[6].numElems);
	(void) memcpy(Out_L + busInfo[7].offset, &_Out_LBUS.AverageAxleSpeed, busInfo[7].elemSize * busInfo[7].numElems);
	(void) memcpy(Out_L + busInfo[8].offset, &_Out_LBUS.deltaAxleProcent, busInfo[8].elemSize * busInfo[8].numElems);
	(void) memcpy(Out_L + busInfo[9].offset, &_Out_LBUS.deltaAxleProcentMAX, busInfo[9].elemSize * busInfo[9].numElems);
	(void) memcpy(Out_L + busInfo[10].offset, &_Out_LBUS.SummSpeedL, busInfo[10].elemSize * busInfo[10].numElems);
	(void) memcpy(Out_L + busInfo[11].offset, &_Out_LBUS.LimitSummSpeedL, busInfo[11].elemSize * busInfo[11].numElems);
	(void) memcpy(Out_L + busInfo[12].offset, &_Out_LBUS.UUqLMAX, busInfo[12].elemSize * busInfo[12].numElems);
	(void) memcpy(Out_L + busInfo[13].offset, &_Out_LBUS.kIqL, busInfo[13].elemSize * busInfo[13].numElems);
	(void) memcpy(Out_L + busInfo[14].offset, &_Out_LBUS.URsAlpha_L, busInfo[14].elemSize * busInfo[14].numElems);
	(void) memcpy(Out_L + busInfo[15].offset, &_Out_LBUS.URsBeta_L, busInfo[15].elemSize * busInfo[15].numElems);
	(void) memcpy(Out_L + busInfo[16].offset, &_Out_LBUS.ULsAlpha_L, busInfo[16].elemSize * busInfo[16].numElems);
	(void) memcpy(Out_L + busInfo[17].offset, &_Out_LBUS.ULsBeta_L, busInfo[17].elemSize * busInfo[17].numElems);
	(void) memcpy(Out_L + busInfo[18].offset, &_Out_LBUS.SpeedLz, busInfo[18].elemSize * busInfo[18].numElems);
	(void) memcpy(Out_L + busInfo[19].offset, &_Out_LBUS.SpeedL, busInfo[19].elemSize * busInfo[19].numElems);
	(void) memcpy(Out_L + busInfo[20].offset, &_Out_LBUS.Udz, busInfo[20].elemSize * busInfo[20].numElems);
	(void) memcpy(Out_L + busInfo[21].offset, &_Out_LBUS.Drive, busInfo[21].elemSize * busInfo[21].numElems);
	(void) memcpy(Out_L + busInfo[22].offset, &_Out_LBUS.Brake, busInfo[22].elemSize * busInfo[22].numElems);
	(void) memcpy(Out_L + busInfo[23].offset, &_Out_LBUS.Debug, busInfo[23].elemSize * busInfo[23].numElems);
	(void) memcpy(Out_L + busInfo[24].offset, &_Out_LBUS.ThetaL, busInfo[24].elemSize * busInfo[24].numElems);
	(void) memcpy(Out_L + busInfo[25].offset, &_Out_LBUS.PowerMax, busInfo[25].elemSize * busInfo[25].numElems);
	(void) memcpy(Out_L + busInfo[26].offset, &_Out_LBUS.Ud, busInfo[26].elemSize * busInfo[26].numElems);
	(void) memcpy(Out_L + busInfo[27].offset, &_Out_LBUS.IaL, busInfo[27].elemSize * busInfo[27].numElems);
	(void) memcpy(Out_L + busInfo[28].offset, &_Out_LBUS.IbL, busInfo[28].elemSize * busInfo[28].numElems);
	(void) memcpy(Out_L + busInfo[29].offset, &_Out_LBUS.IcL, busInfo[29].elemSize * busInfo[29].numElems);
	(void) memcpy(Out_L + busInfo[30].offset, &_Out_LBUS.IAlphaL, busInfo[30].elemSize * busInfo[30].numElems);
	(void) memcpy(Out_L + busInfo[31].offset, &_Out_LBUS.IBetaL, busInfo[31].elemSize * busInfo[31].numElems);
	(void) memcpy(Out_L + busInfo[32].offset, &_Out_LBUS.IdzL, busInfo[32].elemSize * busInfo[32].numElems);
	(void) memcpy(Out_L + busInfo[33].offset, &_Out_LBUS.IdL, busInfo[33].elemSize * busInfo[33].numElems);
	(void) memcpy(Out_L + busInfo[34].offset, &_Out_LBUS.SIdL, busInfo[34].elemSize * busInfo[34].numElems);
	(void) memcpy(Out_L + busInfo[35].offset, &_Out_LBUS.DeltaIdOldL, busInfo[35].elemSize * busInfo[35].numElems);
	(void) memcpy(Out_L + busInfo[36].offset, &_Out_LBUS.DeltaIdL, busInfo[36].elemSize * busInfo[36].numElems);
	(void) memcpy(Out_L + busInfo[37].offset, &_Out_LBUS.UUdL, busInfo[37].elemSize * busInfo[37].numElems);
	(void) memcpy(Out_L + busInfo[38].offset, &_Out_LBUS.IqzL, busInfo[38].elemSize * busInfo[38].numElems);
	(void) memcpy(Out_L + busInfo[39].offset, &_Out_LBUS.IqL, busInfo[39].elemSize * busInfo[39].numElems);
	(void) memcpy(Out_L + busInfo[40].offset, &_Out_LBUS.SIqL, busInfo[40].elemSize * busInfo[40].numElems);
	(void) memcpy(Out_L + busInfo[41].offset, &_Out_LBUS.DeltaIqOldL, busInfo[41].elemSize * busInfo[41].numElems);
	(void) memcpy(Out_L + busInfo[42].offset, &_Out_LBUS.DeltaIqL, busInfo[42].elemSize * busInfo[42].numElems);
	(void) memcpy(Out_L + busInfo[43].offset, &_Out_LBUS.UUqL, busInfo[43].elemSize * busInfo[43].numElems);
	(void) memcpy(Out_L + busInfo[44].offset, &_Out_LBUS.UdSIL, busInfo[44].elemSize * busInfo[44].numElems);
	(void) memcpy(Out_L + busInfo[45].offset, &_Out_LBUS.UqSIL, busInfo[45].elemSize * busInfo[45].numElems);
	(void) memcpy(Out_L + busInfo[46].offset, &_Out_LBUS.E_ampL, busInfo[46].elemSize * busInfo[46].numElems);
	(void) memcpy(Out_L + busInfo[47].offset, &_Out_LBUS.fE_ampL, busInfo[47].elemSize * busInfo[47].numElems);
	(void) memcpy(Out_L + busInfo[48].offset, &_Out_LBUS.UAlphaSIL, busInfo[48].elemSize * busInfo[48].numElems);
	(void) memcpy(Out_L + busInfo[49].offset, &_Out_LBUS.UBetaSIL, busInfo[49].elemSize * busInfo[49].numElems);
	(void) memcpy(Out_L + busInfo[50].offset, &_Out_LBUS.DeltaIAlphaL, busInfo[50].elemSize * busInfo[50].numElems);
	(void) memcpy(Out_L + busInfo[51].offset, &_Out_LBUS.DeltaIBetaL, busInfo[51].elemSize * busInfo[51].numElems);
	(void) memcpy(Out_L + busInfo[52].offset, &_Out_LBUS.OldIAlphaL, busInfo[52].elemSize * busInfo[52].numElems);
	(void) memcpy(Out_L + busInfo[53].offset, &_Out_LBUS.OldIBetaL, busInfo[53].elemSize * busInfo[53].numElems);
	(void) memcpy(Out_L + busInfo[54].offset, &_Out_LBUS.EAlphaInstL, busInfo[54].elemSize * busInfo[54].numElems);
	(void) memcpy(Out_L + busInfo[55].offset, &_Out_LBUS.EBetaInstL, busInfo[55].elemSize * busInfo[55].numElems);
	(void) memcpy(Out_L + busInfo[56].offset, &_Out_LBUS.E_MaxL, busInfo[56].elemSize * busInfo[56].numElems);
	(void) memcpy(Out_L + busInfo[57].offset, &_Out_LBUS.E_LineL, busInfo[57].elemSize * busInfo[57].numElems);
	(void) memcpy(Out_L + busInfo[58].offset, &_Out_LBUS.Ez_ampL, busInfo[58].elemSize * busInfo[58].numElems);
	(void) memcpy(Out_L + busInfo[59].offset, &_Out_LBUS.SEL, busInfo[59].elemSize * busInfo[59].numElems);
	(void) memcpy(Out_L + busInfo[60].offset, &_Out_LBUS.IqLCurLim, busInfo[60].elemSize * busInfo[60].numElems);
	(void) memcpy(Out_L + busInfo[61].offset, &_Out_LBUS.IqLMAX, busInfo[61].elemSize * busInfo[61].numElems);
	(void) memcpy(Out_L + busInfo[62].offset, &_Out_LBUS.fIqLMAX, busInfo[62].elemSize * busInfo[62].numElems);
	(void) memcpy(Out_L + busInfo[63].offset, &_Out_LBUS.UAlphaL, busInfo[63].elemSize * busInfo[63].numElems);
	(void) memcpy(Out_L + busInfo[64].offset, &_Out_LBUS.UBetaL, busInfo[64].elemSize * busInfo[64].numElems);
	(void) memcpy(Out_L + busInfo[65].offset, &_Out_LBUS.UUAL, busInfo[65].elemSize * busInfo[65].numElems);
	(void) memcpy(Out_L + busInfo[66].offset, &_Out_LBUS.UUBL, busInfo[66].elemSize * busInfo[66].numElems);
	(void) memcpy(Out_L + busInfo[67].offset, &_Out_LBUS.UUCL, busInfo[67].elemSize * busInfo[67].numElems);
	(void) memcpy(Out_L + busInfo[68].offset, &_Out_LBUS.ChopReg, busInfo[68].elemSize * busInfo[68].numElems);
	(void) memcpy(Out_L + busInfo[69].offset, &_Out_LBUS.UUqzL, busInfo[69].elemSize * busInfo[69].numElems);
	(void) memcpy(Out_L + busInfo[70].offset, &_Out_LBUS.fUmL, busInfo[70].elemSize * busInfo[70].numElems);
	(void) memcpy(Out_L + busInfo[71].offset, &_Out_LBUS.UmL, busInfo[71].elemSize * busInfo[71].numElems);
	(void) memcpy(Out_L + busInfo[72].offset, &_Out_LBUS.DeltaIdzL, busInfo[72].elemSize * busInfo[72].numElems);
	(void) memcpy(Out_L + busInfo[73].offset, &_Out_LBUS.dEL, busInfo[73].elemSize * busInfo[73].numElems);
	(void) memcpy(Out_L + busInfo[74].offset, &_Out_LBUS.sdEL, busInfo[74].elemSize * busInfo[74].numElems);
	(void) memcpy(Out_L + busInfo[75].offset, &_Out_LBUS.UkdL, busInfo[75].elemSize * busInfo[75].numElems);
	(void) memcpy(Out_L + busInfo[76].offset, &_Out_LBUS.UkqL, busInfo[76].elemSize * busInfo[76].numElems);
	(void) memcpy(Out_L + busInfo[77].offset, &_Out_LBUS.ThetaSlipL, busInfo[77].elemSize * busInfo[77].numElems);
	(void) memcpy(Out_L + busInfo[78].offset, &_Out_LBUS.fThetaL, busInfo[78].elemSize * busInfo[78].numElems);
	(void) memcpy(Out_L + busInfo[79].offset, &_Out_LBUS.EbyFreqL, busInfo[79].elemSize * busInfo[79].numElems);
	(void) memcpy(Out_L + busInfo[80].offset, &_Out_LBUS.LmL16, busInfo[80].elemSize * busInfo[80].numElems);
	(void) memcpy(Out_L + busInfo[81].offset, &_Out_LBUS.FreqL16, busInfo[81].elemSize * busInfo[81].numElems);
	(void) memcpy(Out_L + busInfo[82].offset, &_Out_LBUS.AFSpeedzL16, busInfo[82].elemSize * busInfo[82].numElems);
	(void) memcpy(Out_L + busInfo[83].offset, &_Out_LBUS.DeltaSpeedL, busInfo[83].elemSize * busInfo[83].numElems);
	(void) memcpy(Out_L + busInfo[84].offset, &_Out_LBUS.SpeedLz1_16, busInfo[84].elemSize * busInfo[84].numElems);
	(void) memcpy(Out_L + busInfo[85].offset, &_Out_LBUS.DeltaSpeedL1, busInfo[85].elemSize * busInfo[85].numElems);
	(void) memcpy(Out_L + busInfo[86].offset, &_Out_LBUS.PowerL, busInfo[86].elemSize * busInfo[86].numElems);
	(void) memcpy(Out_L + busInfo[87].offset, &_Out_LBUS.PowerL16, busInfo[87].elemSize * busInfo[87].numElems);
	(void) memcpy(Out_L + busInfo[88].offset, &_Out_LBUS.Iaz, busInfo[88].elemSize * busInfo[88].numElems);
	(void) memcpy(Out_L + busInfo[89].offset, &_Out_LBUS.Ibz, busInfo[89].elemSize * busInfo[89].numElems);
	(void) memcpy(Out_L + busInfo[90].offset, &_Out_LBUS.Icz, busInfo[90].elemSize * busInfo[90].numElems);
	(void) memcpy(Out_L + busInfo[91].offset, &_Out_LBUS.IAlphaz, busInfo[91].elemSize * busInfo[91].numElems);
	(void) memcpy(Out_L + busInfo[92].offset, &_Out_LBUS.Ibetaz, busInfo[92].elemSize * busInfo[92].numElems);
	(void) memcpy(Out_L + busInfo[93].offset, &_Out_LBUS.ImL, busInfo[93].elemSize * busInfo[93].numElems);
	(void) memcpy(Out_L + busInfo[94].offset, &_Out_LBUS.iffL, busInfo[94].elemSize * busInfo[94].numElems);
	(void) memcpy(Out_L + busInfo[95].offset, &_Out_LBUS.IfRMSL, busInfo[95].elemSize * busInfo[95].numElems);
	(void) memcpy(Out_L + busInfo[96].offset, &_Out_LBUS.AmplL, busInfo[96].elemSize * busInfo[96].numElems);
	(void) memcpy(Out_L + busInfo[97].offset, &_Out_LBUS.AlphaL, busInfo[97].elemSize * busInfo[97].numElems);
	(void) memcpy(Out_R + busInfo[98].offset, &_Out_RBUS.DeltaSpeedRCruize, busInfo[98].elemSize * busInfo[98].numElems);
	(void) memcpy(Out_R + busInfo[99].offset, &_Out_RBUS.SpeedRzCruize, busInfo[99].elemSize * busInfo[99].numElems);
	(void) memcpy(Out_R + busInfo[100].offset, &_Out_RBUS.DeltaSpeedRABS, busInfo[100].elemSize * busInfo[100].numElems);
	(void) memcpy(Out_R + busInfo[101].offset, &_Out_RBUS.SummSpeedR, busInfo[101].elemSize * busInfo[101].numElems);
	(void) memcpy(Out_R + busInfo[102].offset, &_Out_RBUS.UUqRMAX, busInfo[102].elemSize * busInfo[102].numElems);
	(void) memcpy(Out_R + busInfo[103].offset, &_Out_RBUS.kIqR, busInfo[103].elemSize * busInfo[103].numElems);
	(void) memcpy(Out_R + busInfo[104].offset, &_Out_RBUS.URsAlpha_R, busInfo[104].elemSize * busInfo[104].numElems);
	(void) memcpy(Out_R + busInfo[105].offset, &_Out_RBUS.URsBeta_R, busInfo[105].elemSize * busInfo[105].numElems);
	(void) memcpy(Out_R + busInfo[106].offset, &_Out_RBUS.ULsAlpha_R, busInfo[106].elemSize * busInfo[106].numElems);
	(void) memcpy(Out_R + busInfo[107].offset, &_Out_RBUS.ULsBeta_R, busInfo[107].elemSize * busInfo[107].numElems);
	(void) memcpy(Out_R + busInfo[108].offset, &_Out_RBUS.SpeedRz, busInfo[108].elemSize * busInfo[108].numElems);
	(void) memcpy(Out_R + busInfo[109].offset, &_Out_RBUS.SpeedR, busInfo[109].elemSize * busInfo[109].numElems);
	(void) memcpy(Out_R + busInfo[110].offset, &_Out_RBUS.IaR, busInfo[110].elemSize * busInfo[110].numElems);
	(void) memcpy(Out_R + busInfo[111].offset, &_Out_RBUS.IbR, busInfo[111].elemSize * busInfo[111].numElems);
	(void) memcpy(Out_R + busInfo[112].offset, &_Out_RBUS.IcR, busInfo[112].elemSize * busInfo[112].numElems);
	(void) memcpy(Out_R + busInfo[113].offset, &_Out_RBUS.IAlphaR, busInfo[113].elemSize * busInfo[113].numElems);
	(void) memcpy(Out_R + busInfo[114].offset, &_Out_RBUS.IBetaR, busInfo[114].elemSize * busInfo[114].numElems);
	(void) memcpy(Out_R + busInfo[115].offset, &_Out_RBUS.IdzR, busInfo[115].elemSize * busInfo[115].numElems);
	(void) memcpy(Out_R + busInfo[116].offset, &_Out_RBUS.IdR, busInfo[116].elemSize * busInfo[116].numElems);
	(void) memcpy(Out_R + busInfo[117].offset, &_Out_RBUS.SIdR, busInfo[117].elemSize * busInfo[117].numElems);
	(void) memcpy(Out_R + busInfo[118].offset, &_Out_RBUS.DeltaIdOldR, busInfo[118].elemSize * busInfo[118].numElems);
	(void) memcpy(Out_R + busInfo[119].offset, &_Out_RBUS.DeltaIdR, busInfo[119].elemSize * busInfo[119].numElems);
	(void) memcpy(Out_R + busInfo[120].offset, &_Out_RBUS.UUdR, busInfo[120].elemSize * busInfo[120].numElems);
	(void) memcpy(Out_R + busInfo[121].offset, &_Out_RBUS.IqzR, busInfo[121].elemSize * busInfo[121].numElems);
	(void) memcpy(Out_R + busInfo[122].offset, &_Out_RBUS.IqR, busInfo[122].elemSize * busInfo[122].numElems);
	(void) memcpy(Out_R + busInfo[123].offset, &_Out_RBUS.SIqR, busInfo[123].elemSize * busInfo[123].numElems);
	(void) memcpy(Out_R + busInfo[124].offset, &_Out_RBUS.DeltaIqOldR, busInfo[124].elemSize * busInfo[124].numElems);
	(void) memcpy(Out_R + busInfo[125].offset, &_Out_RBUS.DeltaIqR, busInfo[125].elemSize * busInfo[125].numElems);
	(void) memcpy(Out_R + busInfo[126].offset, &_Out_RBUS.UUqR, busInfo[126].elemSize * busInfo[126].numElems);
	(void) memcpy(Out_R + busInfo[127].offset, &_Out_RBUS.UdSIR, busInfo[127].elemSize * busInfo[127].numElems);
	(void) memcpy(Out_R + busInfo[128].offset, &_Out_RBUS.UqSIR, busInfo[128].elemSize * busInfo[128].numElems);
	(void) memcpy(Out_R + busInfo[129].offset, &_Out_RBUS.E_ampR, busInfo[129].elemSize * busInfo[129].numElems);
	(void) memcpy(Out_R + busInfo[130].offset, &_Out_RBUS.fE_ampR, busInfo[130].elemSize * busInfo[130].numElems);
	(void) memcpy(Out_R + busInfo[131].offset, &_Out_RBUS.UAlphaSIR, busInfo[131].elemSize * busInfo[131].numElems);
	(void) memcpy(Out_R + busInfo[132].offset, &_Out_RBUS.UBetaSIR, busInfo[132].elemSize * busInfo[132].numElems);
	(void) memcpy(Out_R + busInfo[133].offset, &_Out_RBUS.DeltaIAlphaR, busInfo[133].elemSize * busInfo[133].numElems);
	(void) memcpy(Out_R + busInfo[134].offset, &_Out_RBUS.DeltaIBetaR, busInfo[134].elemSize * busInfo[134].numElems);
	(void) memcpy(Out_R + busInfo[135].offset, &_Out_RBUS.OldIAlphaR, busInfo[135].elemSize * busInfo[135].numElems);
	(void) memcpy(Out_R + busInfo[136].offset, &_Out_RBUS.OldIBetaR, busInfo[136].elemSize * busInfo[136].numElems);
	(void) memcpy(Out_R + busInfo[137].offset, &_Out_RBUS.EAlphaInstR, busInfo[137].elemSize * busInfo[137].numElems);
	(void) memcpy(Out_R + busInfo[138].offset, &_Out_RBUS.EBetaInstR, busInfo[138].elemSize * busInfo[138].numElems);
	(void) memcpy(Out_R + busInfo[139].offset, &_Out_RBUS.E_MaxR, busInfo[139].elemSize * busInfo[139].numElems);
	(void) memcpy(Out_R + busInfo[140].offset, &_Out_RBUS.E_LineR, busInfo[140].elemSize * busInfo[140].numElems);
	(void) memcpy(Out_R + busInfo[141].offset, &_Out_RBUS.Ez_ampR, busInfo[141].elemSize * busInfo[141].numElems);
	(void) memcpy(Out_R + busInfo[142].offset, &_Out_RBUS.SER, busInfo[142].elemSize * busInfo[142].numElems);
	(void) memcpy(Out_R + busInfo[143].offset, &_Out_RBUS.IqRCurLim, busInfo[143].elemSize * busInfo[143].numElems);
	(void) memcpy(Out_R + busInfo[144].offset, &_Out_RBUS.IqRMAX, busInfo[144].elemSize * busInfo[144].numElems);
	(void) memcpy(Out_R + busInfo[145].offset, &_Out_RBUS.fIqRMAX, busInfo[145].elemSize * busInfo[145].numElems);
	(void) memcpy(Out_R + busInfo[146].offset, &_Out_RBUS.UAlphaR, busInfo[146].elemSize * busInfo[146].numElems);
	(void) memcpy(Out_R + busInfo[147].offset, &_Out_RBUS.UBetaR, busInfo[147].elemSize * busInfo[147].numElems);
	(void) memcpy(Out_R + busInfo[148].offset, &_Out_RBUS.UUAR, busInfo[148].elemSize * busInfo[148].numElems);
	(void) memcpy(Out_R + busInfo[149].offset, &_Out_RBUS.UUBR, busInfo[149].elemSize * busInfo[149].numElems);
	(void) memcpy(Out_R + busInfo[150].offset, &_Out_RBUS.UUCR, busInfo[150].elemSize * busInfo[150].numElems);
	(void) memcpy(Out_R + busInfo[151].offset, &_Out_RBUS.ChopReg, busInfo[151].elemSize * busInfo[151].numElems);
	(void) memcpy(Out_R + busInfo[152].offset, &_Out_RBUS.UUqzR, busInfo[152].elemSize * busInfo[152].numElems);
	(void) memcpy(Out_R + busInfo[153].offset, &_Out_RBUS.fUmR, busInfo[153].elemSize * busInfo[153].numElems);
	(void) memcpy(Out_R + busInfo[154].offset, &_Out_RBUS.UmR, busInfo[154].elemSize * busInfo[154].numElems);
	(void) memcpy(Out_R + busInfo[155].offset, &_Out_RBUS.DeltaIdzR, busInfo[155].elemSize * busInfo[155].numElems);
	(void) memcpy(Out_R + busInfo[156].offset, &_Out_RBUS.dUUqR, busInfo[156].elemSize * busInfo[156].numElems);
	(void) memcpy(Out_R + busInfo[157].offset, &_Out_RBUS.sdUUqR, busInfo[157].elemSize * busInfo[157].numElems);
	(void) memcpy(Out_R + busInfo[158].offset, &_Out_RBUS.UkdR, busInfo[158].elemSize * busInfo[158].numElems);
	(void) memcpy(Out_R + busInfo[159].offset, &_Out_RBUS.UkqR, busInfo[159].elemSize * busInfo[159].numElems);
	(void) memcpy(Out_R + busInfo[160].offset, &_Out_RBUS.ThetaSlipR, busInfo[160].elemSize * busInfo[160].numElems);
	(void) memcpy(Out_R + busInfo[161].offset, &_Out_RBUS.fThetaR, busInfo[161].elemSize * busInfo[161].numElems);
	(void) memcpy(Out_R + busInfo[162].offset, &_Out_RBUS.EbyFreqR, busInfo[162].elemSize * busInfo[162].numElems);
	(void) memcpy(Out_R + busInfo[163].offset, &_Out_RBUS.RmR16, busInfo[163].elemSize * busInfo[163].numElems);
	(void) memcpy(Out_R + busInfo[164].offset, &_Out_RBUS.FreqR16, busInfo[164].elemSize * busInfo[164].numElems);
	(void) memcpy(Out_R + busInfo[165].offset, &_Out_RBUS.AFSpeedzR16, busInfo[165].elemSize * busInfo[165].numElems);
	(void) memcpy(Out_R + busInfo[166].offset, &_Out_RBUS.DeltaSpeedR, busInfo[166].elemSize * busInfo[166].numElems);
	(void) memcpy(Out_R + busInfo[167].offset, &_Out_RBUS.SpeedRz1_16, busInfo[167].elemSize * busInfo[167].numElems);
	(void) memcpy(Out_R + busInfo[168].offset, &_Out_RBUS.DeltaSpeedR1, busInfo[168].elemSize * busInfo[168].numElems);
	(void) memcpy(Out_R + busInfo[169].offset, &_Out_RBUS.AmplR, busInfo[169].elemSize * busInfo[169].numElems);
	(void) memcpy(Out_R + busInfo[170].offset, &_Out_RBUS.AlphaR, busInfo[170].elemSize * busInfo[170].numElems);
	(void) memcpy(Out_R + busInfo[171].offset, &_Out_RBUS.PowerR, busInfo[171].elemSize * busInfo[171].numElems);
	(void) memcpy(Out_R + busInfo[172].offset, &_Out_RBUS.PowerR16, busInfo[172].elemSize * busInfo[172].numElems);

}

/* Function: mdlTerminate =====================================================
 * Abstract:
 *    In this function, you should perform any actions that are necessary
 *    at the termination of a simulation.  For example, if memory was
 *    allocated in mdlStart, this is the place to free it.
 */
static void mdlTerminate(SimStruct *S)
{
    /* Free stored bus information */
    busInfoStruct *busInfo = (busInfoStruct *) ssGetUserData(S);
    if(busInfo != NULL) {
        free(busInfo);
    }

}

static int_T GetRTWEnvironmentMode(SimStruct *S)
{
    int_T status = -1;
    mxArray *plhs[1];
    mxArray *prhs[1];
    mxArray * err;
    
    /*
     * Get the name of the Simulink block diagram
     */
    prhs[0] = mxCreateString(ssGetModelName(ssGetRootSS(S)));
    plhs[0] = NULL;
    
    /*
     * Call "isSimulationTarget = rtwenvironmentmode(modelName)" in MATLAB
     */
    err = mexCallMATLABWithTrap(1, plhs, 1, prhs, "rtwenvironmentmode");
    mxDestroyArray(prhs[0]);
    
    /*
     * Set the error status if an error occurred
     */
    if (err) {
        if (plhs[0]) {
            mxDestroyArray(plhs[0]);
            plhs[0] = NULL;
        }
        ssSetErrorStatus(S, "Unknown error during call to 'rtwenvironmentmode'.");
        return -1;
    }
    
    /*
     * Get the value returned by rtwenvironmentmode(modelName)
    */
    if (plhs[0]) {
        status = (int_T) (mxGetScalar(plhs[0]) != 0);
        mxDestroyArray(plhs[0]);
        plhs[0] = NULL;
    }
    
    return (status);
}

#ifdef  MATLAB_MEX_FILE    /* Is this file being compiled as a MEX-file? */
#include "simulink.c"      /* MEX-file interface mechanism */
#else
#include "cg_sfun.h"       /* Code generation registration function */
#endif



